name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: quay.io/ovirt/vdsm-test-centos-8
    steps:
    - uses: actions/checkout@v2
    - name: Run linters
      run: ./automation/lint.sh
  test-storage:
    env:
      TRAVIS_CI: 1
    runs-on: ubuntu-latest
    container:
      image: quay.io/ovirt/vdsm-test-centos-8
      # Required to create loop devices.
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Run storage tests
      run: ./automation/tests-storage.sh
